PRICE-54 User is unable to log in into the blocked account
dorim-group/autotests pull request #5
Opened 2024-10-08 12:40 UTC by Snowfox21

Добавил тестовые данные для заблокированного аккаунта, добавил консты для текста ошибки

2024-10-08 12:59 UTC, tkachukanton requested changes

2024-10-08 12:59 UTC, tkachukanton commented on cypress/e2e/invalid-data/info/invalidInfo.js
> +export const urls = {
не нужен отдельный файл invalidInfo.js
давай и урлы и текст переместим уже в существующий validInfo.js так как это все валидные данные
негативный только сам тест

2024-10-08 12:59 UTC, tkachukanton commented on cypress/e2e/signIn/PRICE-54.User is unable to log in with the blocked account.cy.js
> +      cy.get(signInSelectors.invalidCredsPopup) //Судя по всему, все модалки с ошибкой имеют один селектор и отличаются лишь содержимым
встречал модалки с 500 ошибкой, там селектор отличался, тест падал
если в данном случае совпадает модалка с кейсом когда неверные креды, то давай более общим названием переменную назовем
типа errorPopup или вроде того

2024-10-08 12:59 UTC, tkachukanton commented on cypress/support/commands.js
> +    cy.wait("@signIn").then((interception) => {
предлагаю такую конструкцию здесь
  const statusCode = interception.response.statusCode;
  if (expectSuccess === true) {
    expect(statusCode).to.eq(200);
    cy.url().should("include", urls.productSelectioManual)
  } else if (expectSuccess === 'blocked') {
    expect(statusCode).to.eq(403);
  } else if (expectSuccess === false) {
    expect(statusCode).to.eq(401);
  }
и при вызове функции в самом тесте, в параметре expectSuccess мы четко будем прописывать что ожидаем (в данном случае blocked)
в чем преимущество:
-мы явно используем значения (success, failed,blocked), это более читаемо с точки зрения кода
-можем расширить на другие случаи, к примеру deleted, expired и тд
-меньше повторений проверок статус кода

2024-10-08 13:22 UTC, tkachukanton commented on cypress/support/commands.js
> +    cy.wait("@signIn").then((interception) => {
обсудили, изменение в этом файле не требуется
будем менять логику в файле

2024-10-09 07:35 UTC, tkachukanton commented on cypress/support/commands.js
> +  ({ phone, password, expectSuccess = true }) => {
expectSuccess = true выходит что этот параметр больше не нужен

2024-10-09 08:12 UTC, Snowfox21 reviewed
@tkachukanton Убрал expected status, при прогоне обнаружил, что у себя в тесте не заменил локаторы, исправил тоже. Все остальные изменения - форматирование кода by Prettier

2024-10-09 09:59 UTC, merged